# Generated by Django 5.0.3 on 2024-03-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(blank=True, max_length=100, null=True)),
                ('cat_image', models.ImageField(blank=True, null=True, upload_to='category_pics/')),
                ('cat_description', models.TextField()),
                ('is_listed', models.BooleanField(default=True)),
            ],
        ),
    ]
