# Generated by Django 5.0.3 on 2024-03-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_listed',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
